"""Shared constants for the task orchestrator core package."""

API_VERSION = "v1"
NODE_NAME = "task_orchestrator"
ACTION_EXECUTE_TASK = "/task_orchestrator/execute_task"
TOPIC_ACTIVE_TASKS = "/task_orchestrator/active_tasks"
TOPIC_RESULTS = "/task_orchestrator/results"
TOPIC_EVENTS = "/task_orchestrator/events"
TOPIC_FEEDBACK = "/task_orchestrator/feedback"
SERVICE_LIST_TASKS = "/task_orchestrator/list_tasks"
SERVICE_GET_TASK = "/task_orchestrator/get_task"
SERVICE_CANCEL_TASKS = "/task_orchestrator/cancel_tasks"
SERVICE_PAUSE_TASKS = "/task_orchestrator/pause_tasks"
SERVICE_RESUME_TASKS = "/task_orchestrator/resume_tasks"
SERVICE_VALIDATE_TASK = "/task_orchestrator/validate_task"
SERVICE_REGISTER_AGENT = "/task_orchestrator/register_agent"
SERVICE_LIST_AGENTS = "/task_orchestrator/list_agents"
SERVICE_CLAIM_MISSION = "/task_orchestrator/claim_mission"
SERVICE_RELEASE_MISSION = "/task_orchestrator/release_mission"
SERVICE_VALIDATE_MISSION = "/task_orchestrator/validate_mission"
SERVICE_SUBMIT_MISSION = "/task_orchestrator/submit_mission"
SERVICE_CANCEL_MISSION = "/task_orchestrator/cancel_mission"
SERVICE_PAUSE_MISSION = "/task_orchestrator/pause_mission"
SERVICE_RESUME_MISSION = "/task_orchestrator/resume_mission"
SERVICE_RETRY_MISSION = "/task_orchestrator/retry_mission"
SERVICE_GET_MISSION_STATE = "/task_orchestrator/get_mission_state"
