"""Shared constants for the task orchestrator core package."""

API_VERSION = "v1beta1"
NODE_NAME = "task_orchestrator"
ACTION_EXECUTE_TASK = "/task_orchestrator/execute_task"
TOPIC_ACTIVE_TASKS = "/task_orchestrator/active_tasks"
TOPIC_RESULTS = "/task_orchestrator/results"
TOPIC_EVENTS = "/task_orchestrator/events"
TOPIC_FEEDBACK = "/task_orchestrator/feedback"
SERVICE_LIST_TASKS = "/task_orchestrator/list_tasks"
SERVICE_GET_TASK = "/task_orchestrator/get_task"
SERVICE_CANCEL_TASKS = "/task_orchestrator/cancel_tasks"
SERVICE_PAUSE_TASKS = "/task_orchestrator/pause_tasks"
SERVICE_RESUME_TASKS = "/task_orchestrator/resume_tasks"
SERVICE_VALIDATE_TASK = "/task_orchestrator/validate_task"
